=== PowerAndMones/lineagehighfive/server/L2J_Mobius_CT_2.6_HighFive/dist/game/data/xsd/spawns.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="spawn" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded"><xs:element name="AIData" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element type="xs:nonNegativeInteger" name="aggroRange" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:boolean" name="disableRandomAnimation" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:boolean" name="disableRandomWalk" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:integer" name="fleeX" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:integer" name="fleeY" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:integer" name="fleeZ" minOccurs="0" maxOccurs="1"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="territory" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="node" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:int" name="x" use="required"/>
														<xs:attribute type="xs:int" name="y" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional"/>
									<xs:attribute type="xs:string" name="shape" use="optional"/>
									<xs:attribute type="xs:short" name="minZ" use="required"/>
									<xs:attribute type="xs:short" name="maxZ" use="required"/>
									<xs:attribute type="xs:int" name="rad" use="optional"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="banned_territory" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="node" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:int" name="x" use="required"/>
														<xs:attribute type="xs:int" name="y" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="shape" use="optional"/>
									<xs:attribute type="xs:short" name="minZ" use="required"/>
									<xs:attribute type="xs:short" name="maxZ" use="required"/>
									<xs:attribute type="xs:int" name="rad" use="optional"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="npc" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType mixed="true">
									<xs:sequence minOccurs="0" maxOccurs="unbounded"><xs:element name="parameters" minOccurs="0" maxOccurs="1"><xs:complexType><xs:choice minOccurs="1" maxOccurs="unbounded"><xs:element name="param"><xs:complexType><xs:attribute name="name" type="xs:token" use="required"/><xs:attribute name="value" type="xs:string" use="required"/></xs:complexType></xs:element><xs:element name="skill"><xs:complexType><xs:attribute name="name" type="xs:token" use="required"/><xs:attribute name="id" type="xs:positiveInteger" use="required"/><xs:attribute name="level" type="xs:positiveInteger" use="required"/></xs:complexType></xs:element></xs:choice></xs:complexType></xs:element><xs:element name="minions" minOccurs="0"><xs:complexType><xs:sequence minOccurs="0" maxOccurs="unbounded"><xs:element name="minion"><xs:complexType><xs:attribute name="id" type="xs:positiveInteger"/><xs:attribute name="count" type="xs:positiveInteger"/><xs:attribute name="respawnTime" type="xs:string"/><xs:attribute name="randomRespawn" type="xs:string"/><xs:attribute name="weightpoint" type="xs:nonNegativeInteger"/><xs:attribute name="respawnDelay" type="xs:nonNegativeInteger"/></xs:complexType></xs:element></xs:sequence></xs:complexType></xs:element><xs:element name="locations" minOccurs="0"><xs:complexType><xs:sequence minOccurs="1" maxOccurs="unbounded"><xs:element name="location"><xs:complexType><xs:attribute name="x" type="xs:integer"/><xs:attribute name="y" type="xs:integer"/><xs:attribute name="z" type="xs:integer"/><xs:attribute name="heading" type="xs:integer"/><xs:attribute name="chance" type="xs:double" use="required"/></xs:complexType></xs:element></xs:sequence></xs:complexType></xs:element></xs:sequence><xs:attribute name="id" type="xs:positiveInteger" use="required"/>
											<xs:attribute name="x" type="xs:integer" use="optional"/>
											<xs:attribute name="y" type="xs:integer" use="optional"/>
											<xs:attribute name="z" type="xs:integer" use="optional"/>
											<xs:attribute name="heading" type="xs:integer" use="optional"/>
											<xs:attribute name="count" type="xs:positiveInteger" use="optional"/>
											<xs:attribute name="respawnDelay" type="xs:nonNegativeInteger" use="optional"/>
											<xs:attribute name="respawnRandom" type="xs:nonNegativeInteger" use="optional"/>
											<xs:attribute name="chaseRange" type="xs:nonNegativeInteger" use="optional"/>
											<xs:attribute name="periodOfDay" use="optional">
												<xs:simpleType>
													<xs:restriction base="xs:token">
														<xs:enumeration value="day"/>
														<xs:enumeration value="night"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										<xs:attribute name="dbSave" type="xs:boolean"/><xs:attribute name="dbName" type="xs:string"/></xs:complexType>
							</xs:element>
						<xs:element name="group" minOccurs="0" maxOccurs="unbounded"><xs:complexType><xs:sequence minOccurs="0" maxOccurs="unbounded"><xs:element name="territories" minOccurs="0" maxOccurs="1"><xs:complexType><xs:choice minOccurs="1" maxOccurs="unbounded"><xs:element name="territory" type="territoryDef"/><xs:element name="banned_territory" type="territoryDef"/></xs:choice></xs:complexType></xs:element><xs:element name="npc" minOccurs="0" maxOccurs="unbounded"><xs:complexType mixed="true"><xs:sequence minOccurs="0" maxOccurs="unbounded"><xs:element name="parameters" minOccurs="0" maxOccurs="1"><xs:complexType><xs:choice minOccurs="1" maxOccurs="unbounded"><xs:element name="param"><xs:complexType><xs:attribute name="name" type="xs:token" use="required"/><xs:attribute name="value" type="xs:string" use="required"/></xs:complexType></xs:element></xs:choice></xs:complexType></xs:element><xs:element name="minions" minOccurs="0"><xs:complexType><xs:sequence minOccurs="0" maxOccurs="unbounded"><xs:element name="minion"><xs:complexType><xs:attribute name="id" type="xs:positiveInteger"/><xs:attribute name="count" type="xs:positiveInteger"/><xs:attribute name="respawnTime" type="xs:string"/><xs:attribute name="respawnDelay" type="xs:nonNegativeInteger"/><xs:attribute name="randomRespawn" type="xs:string"/><xs:attribute name="weightpoint" type="xs:nonNegativeInteger"/></xs:complexType></xs:element></xs:sequence></xs:complexType></xs:element></xs:sequence><xs:attribute name="id" type="xs:positiveInteger" use="required"/><xs:attribute name="x" type="xs:integer"/><xs:attribute name="y" type="xs:integer"/><xs:attribute name="z" type="xs:integer"/><xs:attribute name="heading" type="xs:integer"/><xs:attribute name="count" type="xs:positiveInteger"/><xs:attribute name="respawnDelay" type="xs:nonNegativeInteger"/><xs:attribute name="respawnRandom" type="xs:nonNegativeInteger"/><xs:attribute name="chaseRange" type="xs:integer"/><xs:attribute name="periodOfDay" type="xs:token"/><xs:attribute name="zone" type="xs:string"/></xs:complexType></xs:element></xs:sequence><xs:attribute name="name" type="xs:string"/><xs:attribute name="selection" type="xs:string"/></xs:complexType></xs:element><xs:element name="territories" minOccurs="0" maxOccurs="1"><xs:complexType><xs:choice minOccurs="1" maxOccurs="unbounded"><xs:element name="territory" type="territoryDef"/><xs:element name="banned_territory" type="territoryDef"/></xs:choice></xs:complexType></xs:element><xs:element name="parameters" minOccurs="0" maxOccurs="1"><xs:complexType><xs:choice minOccurs="1" maxOccurs="unbounded"><xs:element name="param"><xs:complexType><xs:attribute name="name" type="xs:token" use="required"/><xs:attribute name="value" type="xs:string" use="required"/></xs:complexType></xs:element><xs:element name="skill"><xs:complexType><xs:attribute name="name" type="xs:token" use="required"/><xs:attribute name="id" type="xs:positiveInteger" use="required"/><xs:attribute name="level" type="xs:positiveInteger" use="required"/></xs:complexType></xs:element></xs:choice></xs:complexType></xs:element></xs:choice><xs:attribute type="xs:string" name="name" use="optional"/>
						<xs:attribute type="xs:string" name="zone" use="optional"/>
						<xs:attribute type="xs:string" name="zones" use="optional"/>
						<xs:attribute name="selection" use="optional">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="all"/>
									<xs:enumeration value="random"/>
									<xs:enumeration value="randomFill"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute type="xs:positiveInteger" name="maximumNpc" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="enabled" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>
<xs:complexType name="territoryDef"><xs:choice minOccurs="1" maxOccurs="unbounded"><xs:element name="node"><xs:complexType><xs:attribute name="x" type="xs:integer" use="required"/><xs:attribute name="y" type="xs:integer" use="required"/></xs:complexType></xs:element></xs:choice><xs:attribute name="name" type="xs:string"/><xs:attribute name="minZ" type="xs:integer"/><xs:attribute name="maxZ" type="xs:integer"/></xs:complexType></xs:schema>

=== PowerAndMones/lineagehighfive/server/L2J_Mobius_CT_2.6_HighFive/dist/game/data/spawns/Others/BeautyShop.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/spawns.xsd">
	<!-- La Vie En Rose - Beauty Shop (Salvation 140 port). Coordinates from the Salvation reference datapack. -->
	<spawn name="beauty_shop_giran">
		<npc id="33825" x="81752" y="149631" z="-3464" heading="49153" respawnDelay="60" /> <!-- La Vie En Rose -->
		<npc id="33854" x="81758" y="149574" z="-3464" heading="38013" respawnDelay="60" /> <!-- Beauty Shop Helper -->
		<npc id="33855" x="81743" y="149510" z="-3464" heading="60187" respawnDelay="60" /> <!-- Beauty Shop Helper -->
		<npc id="33857" x="81710" y="149574" z="-3464" heading="56529" respawnDelay="60" /> <!-- Beauty Shop Helper -->
	</spawn>
	<spawn name="beauty_shop_aden">
		<npc id="33825" x="146468" y="27822" z="-2264" heading="65323" respawnDelay="60" /> <!-- La Vie En Rose -->
	</spawn>
	<spawn name="beauty_shop_dion">
		<npc id="33825" x="15145" y="143472" z="-2672" heading="57049" respawnDelay="60" /> <!-- La Vie En Rose -->
	</spawn>
	<spawn name="beauty_shop_rune">
		<npc id="33825" x="43463" y="-48421" z="-792" heading="19404" respawnDelay="60" /> <!-- La Vie En Rose -->
	</spawn>
	<spawn name="beauty_shop_schuttgart">
		<npc id="33825" x="86158" y="-143435" z="-1336" heading="63814" respawnDelay="60" /> <!-- La Vie En Rose -->
	</spawn>
</list>

=== PowerAndMones/lineagehighfive/server/L2J_Mobius_CT_2.6_HighFive/dist/game/data/spawns/Hunters/HuntersVillage.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/spawns.xsd">
	<spawn name="HuntersVillage">
		<group>
			<npc id="30230" x="115116" y="75923" z="-2576" heading="59000" respawnDelay="60" /> <!-- Edroc -->
			<npc id="30231" x="116109" y="75022" z="-2584" heading="57344" respawnDelay="60" /> <!-- Garette -->
			<npc id="30232" x="115271" y="76705" z="-2648" respawnDelay="60" /> <!-- Sorint -->
			<npc id="30233" x="117129" y="76917" z="-2672" heading="34000" respawnDelay="60" /> <!-- Esmeralda -->
			<npc id="30301" x="116646" y="74820" z="-2584" heading="28672" respawnDelay="60" /> <!-- Hally -->
			<npc id="30610" x="117866" y="76483" z="-2688" heading="35768" respawnDelay="60" /> <!-- Cronos -->
			<npc id="30655" x="115791" y="75867" z="-2712" heading="3000" respawnDelay="60" /> <!-- Isael Silvershadow -->
			<npc id="30684" x="115310" y="75447" z="-2576" heading="12288" respawnDelay="60" /> <!-- Viktor -->
			<npc id="30685" x="115647" y="77114" z="-2648" heading="40960" respawnDelay="60" /> <!-- Baxt -->
			<npc id="30686" x="115435" y="76541" z="-2648" heading="12000" respawnDelay="60" /> <!-- Silva -->
			<npc id="30687" x="117649" y="75415" z="-2648" heading="32768" respawnDelay="60" /> <!-- Vergara -->
			<npc id="30688" x="117613" y="75310" z="-2648" heading="24576" respawnDelay="60" /> <!-- Duning -->
			<npc id="30689" x="119673" y="77618" z="-2240" heading="39864" respawnDelay="60" /> <!-- Siria -->
			<npc id="30690" x="119472" y="77835" z="-2240" heading="49152" respawnDelay="60" /> <!-- Luther -->
			<npc id="30691" x="119249" y="77663" z="-2240" respawnDelay="60" /> <!-- Aren Athebaldt -->
			<npc id="30692" x="119892" y="77284" z="-2240" heading="28672" respawnDelay="60" /> <!-- Stedmiel -->
			<npc id="30693" x="119727" y="77137" z="-2240" heading="16384" respawnDelay="60" /> <!-- Queenien -->
			<npc id="30694" x="119043" y="78586" z="-2160" heading="39000" respawnDelay="60" /> <!-- Scraide -->
			<npc id="30695" x="119156" y="78356" z="-2160" heading="28672" respawnDelay="60" /> <!-- Moses -->
			<npc id="30696" x="118890" y="78104" z="-2160" heading="16384" respawnDelay="60" /> <!-- Page -->
			<npc id="30697" x="118887" y="78752" z="-2160" heading="49152" respawnDelay="60" /> <!-- Videlrien -->
			<npc id="30698" x="118571" y="78513" z="-2160" respawnDelay="60" /> <!-- Evelyn -->
			<npc id="30699" x="120249" y="76031" z="-2256" heading="31768" respawnDelay="60" /> <!-- Medown -->
			<npc id="30700" x="120251" y="76247" z="-2264" heading="40960" respawnDelay="60" /> <!-- Prestan -->
			<npc id="30701" x="120180" y="75807" z="-2264" heading="18384" respawnDelay="60" /> <!-- Errickin -->
			<npc id="30702" x="117491" y="77187" z="-2596" heading="60143" respawnDelay="60" /> <!-- Bernard -->
			<npc id="30703" x="117717" y="77273" z="-2584" heading="45056" respawnDelay="60" /> <!-- Colin -->
			<npc id="30704" x="120100" y="74739" z="-2368" heading="31000" respawnDelay="60" /> <!-- Garvarentz -->
			<npc id="30705" x="120079" y="74847" z="-2368" heading="31000" respawnDelay="60" /> <!-- Chakiris -->
			<npc id="30706" x="120039" y="74650" z="-2368" heading="31000" respawnDelay="60" /> <!-- Lazenby -->
			<npc id="30707" x="117129" y="75848" z="-2728" heading="24368" respawnDelay="60" /> <!-- Raigen -->
			<npc id="30708" x="118210" y="76078" z="-2688" heading="32768" respawnDelay="60" /> <!-- Nasign -->
			<npc id="30709" x="114564" y="78107" z="-2592" heading="60929" respawnDelay="60" /> <!-- Norton -->
			<npc id="30710" x="114512" y="77966" z="-2592" heading="42902" respawnDelay="60" /> <!-- Weston -->
			<npc id="30711" x="115032" y="74395" z="-2592" respawnDelay="60" /> <!-- Byron -->
			<npc id="30712" x="115207" y="74239" z="-2592" heading="8953" respawnDelay="60" /> <!-- Makhis -->
			<npc id="30713" x="118437" y="74051" z="-2384" heading="50000" respawnDelay="60" /> <!-- Gardner -->
			<npc id="30714" x="118306" y="74040" z="-2368" heading="50000" respawnDelay="60" /> <!-- Paros -->
			<npc id="30744" x="117980" y="76704" z="-2592" heading="32768" respawnDelay="60" /> <!-- Grey -->
			<npc id="30745" x="115952" y="76000" z="-2721" respawnDelay="60" /> <!-- Tor -->
			<npc id="30746" x="116085" y="74728" z="-2584" heading="10000" respawnDelay="60" /> <!-- Cybellin -->
			<npc id="30764" x="117380" y="75616" z="-2664" heading="26000" respawnDelay="60" /> <!-- Balthazar -->
			<npc id="30831" x="117432" y="76044" z="-2720" heading="15000" respawnDelay="60" /> <!-- Nelson -->
			<!-- <npc id="30990" x="117148" y="76865" z="-2688" heading="34000" respawnDelay="60" /> --> <!-- Lottery Ticket Seller -->
			<npc id="31031" x="116036" y="76319" z="-2720" respawnDelay="60" /> <!-- Broadcasting Tower -->
			<npc id="31051" x="116320" y="74688" z="-2584" heading="16300" respawnDelay="60" /> <!-- Keach -->
			<npc id="31092" x="120493" y="76520" z="-2136" heading="35500" respawnDelay="60" /> <!-- Black Marketeer of Mammon -->
			<npc id="31207" x="117462" y="76074" z="-2712" respawnDelay="60" /> <!-- Sardinia -->
			<npc id="31576" x="116048" y="74716" z="-2584" heading="7000" respawnDelay="60" /> <!-- Berix -->
			<npc id="31603" x="117536" y="77264" z="-2584" heading="56000" respawnDelay="60" /> <!-- Black Cat -->
			<npc id="31604" x="115664" y="77136" z="-2624" heading="50000" respawnDelay="60" /> <!-- Grimst -->
			<npc id="31669" x="117572" y="75592" z="-2648" heading="40000" respawnDelay="60" /> <!-- Onyx -->
			<npc id="31688" x="116144" y="77856" z="-2680" heading="49000" respawnDelay="60" /> <!-- Olympiad Manager -->
			<npc id="31690" x="116096" y="77856" z="-2680" heading="49000" respawnDelay="60" /> <!-- Monument of Heroes -->
			<npc id="32217" x="116080" y="79179" z="-2384" heading="49151" respawnDelay="60" /> <!-- Barta -->
			<npc id="32218" x="115920" y="79179" z="-2384" heading="49151" respawnDelay="60" /> <!-- Miya -->
			<npc id="32219" x="116119" y="79150" z="-2384" heading="49151" respawnDelay="60" /> <!-- Fabnor -->
			<npc id="32220" x="115886" y="79145" z="-2384" heading="49151" respawnDelay="60" /> <!-- Selsia -->
			<npc id="32327" x="116835" y="77219" z="-2696" heading="32767" respawnDelay="60" /> <!-- Adventurers' Guide -->
			<npc id="32478" x="115656" y="76620" z="-2664" heading="60000" respawnDelay="60" /> <!-- Dimensional Merchant -->
			<npc id="32887" x="117410" y="75082" z="-2648" heading="17108" respawnDelay="60" /> <!-- Metar -->
			<npc id="33100" x="116328" y="76905" z="-2728" heading="56899" respawnDelay="60" /> <!-- Lada -->
			<npc id="33462" x="116468" y="77871" z="-2680" heading="40000" respawnDelay="60" /> <!-- Jonadan -->
			<npc id="33495" x="116345" y="74692" z="-2584" heading="15388" respawnDelay="60" /> <!-- Jyamis -->
			<npc id="33587" x="116911" y="77190" z="-2688" heading="32767" respawnDelay="60" /> <!-- Mentor Guide -->
			<npc id="33685" x="116045" y="77812" z="-2680" heading="49811" respawnDelay="60" /> <!-- Mysterious Butler -->
			<npc id="33918" x="116387" y="75384" z="-2712" heading="20745" respawnDelay="60" /> <!-- Aria Furstmater -->
			<npc id="35277" x="116780" y="75504" z="-2720" heading="20000" respawnDelay="60" /> <!-- Manor Manager -->
			<npc id="34018" x="116503" y="75392" z="-2712" heading="12298" respawnDelay="60" /> <!-- Merlot -->
			<npc id="33946" x="116830" y="77297" z="-2698" heading="36736" respawnDelay="60" /> <!-- Adventure Guildsman -->
			<npc id="34267" x="117598" y="77264" z="-2585" heading="53248" respawnDelay="60" /> <!-- Arcturus -->
			<npc id="34357" x="115966" y="76032" z="-2712" heading="0" respawnDelay="60" /> <!-- Orin -->
		</group>
	</spawn>
</list>

=== PowerAndMones/lineagehighfive/server/L2J_Mobius_CT_2.6_HighFive/dist/game/data/spawns/Schuttgart/EarthWyrmCave.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/spawns.xsd">
	<spawn name="EarthWyrmCave">
		<group>
			<!-- Belenora -->
			<npc id="33506" x="75254" y="-182400" z="-9888" heading="40960" />
			<!-- Dark Elf Soldier -->
			<npc id="33507" x="75210" y="-182546" z="-9896" heading="8192" />
			<npc id="33507" x="76280" y="-182298" z="-9888" heading="0" />
			<npc id="33507" x="75106" y="-182365" z="-9888" heading="8192" />
			<npc id="33507" x="75067" y="-182406" z="-9888" heading="8192" />
			<npc id="33507" x="75150" y="-182417" z="-9896" heading="8192" />
			<npc id="33507" x="75249" y="-182497" z="-9896" heading="8192" />
			<npc id="33507" x="75227" y="-182626" z="-9899" heading="8192" />
			<npc id="33507" x="75292" y="-182532" z="-9896" heading="8192" />
			<npc id="33507" x="75177" y="-182587" z="-9888" heading="8192" />
			<npc id="33507" x="75119" y="-182461" z="-9888" heading="8192" />
			<npc id="33507" x="75166" y="-182505" z="-9888" heading="8192" />
			<npc id="33507" x="76333" y="-182254" z="-9888" heading="0" />
			<npc id="33507" x="75259" y="-182579" z="-9896" heading="8192" />
			<npc id="33507" x="75199" y="-182458" z="-9896" heading="8192" />
			<npc id="33507" x="75133" y="-182552" z="-9864" heading="8192" />
			<npc id="33507" x="75032" y="-182453" z="-9888" heading="8192" />
			<!-- Alejandro -->
			<npc id="33502" x="75179" y="-182148" z="-9888" heading="32768" />
			<!-- Dwarf Soldier -->
			<npc id="33503" x="75067" y="-182208" z="-9896" heading="0" />
			<npc id="33503" x="75015" y="-182211" z="-9896" heading="0" />
			<npc id="33503" x="75067" y="-182148" z="-9896" heading="0" />
			<npc id="33503" x="75012" y="-182148" z="-9896" heading="0" />
			<npc id="33503" x="74955" y="-182145" z="-9896" heading="0" />
			<npc id="33503" x="74952" y="-182082" z="-9896" heading="0" />
			<npc id="33503" x="75015" y="-182082" z="-9896" heading="0" />
			<npc id="33503" x="74952" y="-182211" z="-9896" heading="0" />
			<npc id="33503" x="74949" y="-182019" z="-9880" heading="0" />
			<npc id="33503" x="75015" y="-182019" z="-9896" heading="0" />
			<npc id="33503" x="74952" y="-182269" z="-9896" heading="0" />
			<npc id="33503" x="75015" y="-182272" z="-9896" heading="0" />
			<npc id="33503" x="75067" y="-182272" z="-9896" heading="0" />
			<npc id="33503" x="75067" y="-182022" z="-9896" heading="0" />
			<npc id="33503" x="76277" y="-181919" z="-9896" heading="0" />
			<npc id="33503" x="76342" y="-181971" z="-9896" heading="0" />
			<npc id="33503" x="75067" y="-182085" z="-9896" heading="0" />
			<!-- Teleport Device -->
			<npc id="33513" x="75179" y="-181893" z="-9896" heading="0" />
			<!-- Wooden Medic -->
			<npc id="33505" x="75372" y="-181770" z="-9888" heading="24576" />
			<!-- Dwarf Soldier -->
			<npc id="33504" x="75372" y="-181644" z="-9888" heading="45056" />
			<npc id="33504" x="75459" y="-181612" z="-9896" heading="16384" />
			<npc id="33504" x="75287" y="-181685" z="-9896" heading="32768" />
			<npc id="33504" x="75205" y="-181755" z="-9888" heading="0" />
			<!-- Fernando -->
			<!--
			<npc id="33160" x="77154" y="-182196" z="-9888" heading="30708" />
			-->
		</group>
	</spawn>
</list>
