=== PowerAndMones/lineagehighfive/server/L2J_Mobius_CT_2.6_HighFive/dist/game/data/xsd/spawns.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="spawn" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded"><xs:element name="AIData" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element type="xs:nonNegativeInteger" name="aggroRange" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:boolean" name="disableRandomAnimation" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:boolean" name="disableRandomWalk" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:integer" name="fleeX" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:integer" name="fleeY" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:integer" name="fleeZ" minOccurs="0" maxOccurs="1"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="territory" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="node" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:int" name="x" use="required"/>
														<xs:attribute type="xs:int" name="y" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional"/>
									<xs:attribute type="xs:string" name="shape" use="optional"/>
									<xs:attribute type="xs:short" name="minZ" use="required"/>
									<xs:attribute type="xs:short" name="maxZ" use="required"/>
									<xs:attribute type="xs:int" name="rad" use="optional"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="banned_territory" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="node" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:int" name="x" use="required"/>
														<xs:attribute type="xs:int" name="y" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="shape" use="optional"/>
									<xs:attribute type="xs:short" name="minZ" use="required"/>
									<xs:attribute type="xs:short" name="maxZ" use="required"/>
									<xs:attribute type="xs:int" name="rad" use="optional"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="npc" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType mixed="true">
									<xs:sequence minOccurs="0" maxOccurs="unbounded"><xs:element name="parameters" minOccurs="0" maxOccurs="1"><xs:complexType><xs:choice minOccurs="1" maxOccurs="unbounded"><xs:element name="param"><xs:complexType><xs:attribute name="name" type="xs:token" use="required"/><xs:attribute name="value" type="xs:string" use="required"/></xs:complexType></xs:element><xs:element name="skill"><xs:complexType><xs:attribute name="name" type="xs:token" use="required"/><xs:attribute name="id" type="xs:positiveInteger" use="required"/><xs:attribute name="level" type="xs:positiveInteger" use="required"/></xs:complexType></xs:element></xs:choice></xs:complexType></xs:element><xs:element name="minions" minOccurs="0"><xs:complexType><xs:sequence minOccurs="0" maxOccurs="unbounded"><xs:element name="minion"><xs:complexType><xs:attribute name="id" type="xs:positiveInteger"/><xs:attribute name="count" type="xs:positiveInteger"/><xs:attribute name="respawnTime" type="xs:string"/><xs:attribute name="randomRespawn" type="xs:string"/><xs:attribute name="weightpoint" type="xs:nonNegativeInteger"/><xs:attribute name="respawnDelay" type="xs:nonNegativeInteger"/></xs:complexType></xs:element></xs:sequence></xs:complexType></xs:element><xs:element name="locations" minOccurs="0"><xs:complexType><xs:sequence minOccurs="1" maxOccurs="unbounded"><xs:element name="location"><xs:complexType><xs:attribute name="x" type="xs:integer"/><xs:attribute name="y" type="xs:integer"/><xs:attribute name="z" type="xs:integer"/><xs:attribute name="heading" type="xs:integer"/><xs:attribute name="chance" type="xs:double" use="required"/></xs:complexType></xs:element></xs:sequence></xs:complexType></xs:element></xs:sequence><xs:attribute name="id" type="xs:positiveInteger" use="required"/>
											<xs:attribute name="x" type="xs:integer" use="optional"/>
											<xs:attribute name="y" type="xs:integer" use="optional"/>
											<xs:attribute name="z" type="xs:integer" use="optional"/>
											<xs:attribute name="heading" type="xs:integer" use="optional"/>
											<xs:attribute name="count" type="xs:positiveInteger" use="optional"/>
											<xs:attribute name="respawnDelay" type="xs:nonNegativeInteger" use="optional"/>
											<xs:attribute name="respawnRandom" type="xs:nonNegativeInteger" use="optional"/>
											<xs:attribute name="chaseRange" type="xs:nonNegativeInteger" use="optional"/>
											<xs:attribute name="periodOfDay" use="optional">
												<xs:simpleType>
													<xs:restriction base="xs:token">
														<xs:enumeration value="day"/>
														<xs:enumeration value="night"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										<xs:attribute name="dbSave" type="xs:boolean"/><xs:attribute name="dbName" type="xs:string"/></xs:complexType>
							</xs:element>
						<xs:element name="group" minOccurs="0" maxOccurs="unbounded"><xs:complexType><xs:sequence minOccurs="0" maxOccurs="unbounded"><xs:element name="territories" minOccurs="0" maxOccurs="1"><xs:complexType><xs:choice minOccurs="1" maxOccurs="unbounded"><xs:element name="territory" type="territoryDef"/><xs:element name="banned_territory" type="territoryDef"/></xs:choice></xs:complexType></xs:element><xs:element name="npc" minOccurs="0" maxOccurs="unbounded"><xs:complexType mixed="true"><xs:sequence minOccurs="0" maxOccurs="unbounded"><xs:element name="parameters" minOccurs="0" maxOccurs="1"><xs:complexType><xs:choice minOccurs="1" maxOccurs="unbounded"><xs:element name="param"><xs:complexType><xs:attribute name="name" type="xs:token" use="required"/><xs:attribute name="value" type="xs:string" use="required"/></xs:complexType></xs:element></xs:choice></xs:complexType></xs:element><xs:element name="minions" minOccurs="0"><xs:complexType><xs:sequence minOccurs="0" maxOccurs="unbounded"><xs:element name="minion"><xs:complexType><xs:attribute name="id" type="xs:positiveInteger"/><xs:attribute name="count" type="xs:positiveInteger"/><xs:attribute name="respawnTime" type="xs:string"/><xs:attribute name="respawnDelay" type="xs:nonNegativeInteger"/><xs:attribute name="randomRespawn" type="xs:string"/><xs:attribute name="weightpoint" type="xs:nonNegativeInteger"/></xs:complexType></xs:element></xs:sequence></xs:complexType></xs:element></xs:sequence><xs:attribute name="id" type="xs:positiveInteger" use="required"/><xs:attribute name="x" type="xs:integer"/><xs:attribute name="y" type="xs:integer"/><xs:attribute name="z" type="xs:integer"/><xs:attribute name="heading" type="xs:integer"/><xs:attribute name="count" type="xs:positiveInteger"/><xs:attribute name="respawnDelay" type="xs:nonNegativeInteger"/><xs:attribute name="respawnRandom" type="xs:nonNegativeInteger"/><xs:attribute name="chaseRange" type="xs:integer"/><xs:attribute name="periodOfDay" type="xs:token"/><xs:attribute name="zone" type="xs:string"/></xs:complexType></xs:element></xs:sequence><xs:attribute name="name" type="xs:string"/><xs:attribute name="selection" type="xs:string"/></xs:complexType></xs:element><xs:element name="territories" minOccurs="0" maxOccurs="1"><xs:complexType><xs:choice minOccurs="1" maxOccurs="unbounded"><xs:element name="territory" type="territoryDef"/><xs:element name="banned_territory" type="territoryDef"/></xs:choice></xs:complexType></xs:element><xs:element name="parameters" minOccurs="0" maxOccurs="1"><xs:complexType><xs:choice minOccurs="1" maxOccurs="unbounded"><xs:element name="param"><xs:complexType><xs:attribute name="name" type="xs:token" use="required"/><xs:attribute name="value" type="xs:string" use="required"/></xs:complexType></xs:element><xs:element name="skill"><xs:complexType><xs:attribute name="name" type="xs:token" use="required"/><xs:attribute name="id" type="xs:positiveInteger" use="required"/><xs:attribute name="level" type="xs:positiveInteger" use="required"/></xs:complexType></xs:element></xs:choice></xs:complexType></xs:element></xs:choice><xs:attribute type="xs:string" name="name" use="optional"/>
						<xs:attribute type="xs:string" name="zone" use="optional"/>
						<xs:attribute type="xs:string" name="zones" use="optional"/>
						<xs:attribute name="selection" use="optional">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="all"/>
									<xs:enumeration value="random"/>
									<xs:enumeration value="randomFill"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute type="xs:positiveInteger" name="maximumNpc" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="enabled" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>
<xs:complexType name="territoryDef"><xs:choice minOccurs="1" maxOccurs="unbounded"><xs:element name="node"><xs:complexType><xs:attribute name="x" type="xs:integer" use="required"/><xs:attribute name="y" type="xs:integer" use="required"/></xs:complexType></xs:element></xs:choice><xs:attribute name="name" type="xs:string"/><xs:attribute name="minZ" type="xs:integer"/><xs:attribute name="maxZ" type="xs:integer"/></xs:complexType></xs:schema>

=== PowerAndMones/lineagehighfive/server/L2J_Mobius_CT_2.6_HighFive/dist/game/data/spawns/Dion/TownOfDion.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/spawns.xsd">
	<spawn name="TownOfDion">
		<group>
			<npc id="35403" x="17621" y="144920" z="-3032" heading="12288" respawnDelay="60" /> <!-- Ron -->
			<npc id="30057" x="20777" y="144971" z="-3064" heading="53248" respawnDelay="60" /> <!-- Amidol -->
			<npc id="30058" x="20750" y="144432" z="-3064" heading="8192" respawnDelay="60" /> <!-- Holvas -->
			<npc id="30059" x="15631" y="142885" z="-2688" heading="16000" respawnDelay="60" /> <!-- Trisha -->
			<npc id="30060" x="17999" y="144484" z="-3040" heading="6000" respawnDelay="60" /> <!-- Sabrin -->
			<npc id="30061" x="17948" y="144560" z="-3040" heading="6000" respawnDelay="60" /> <!-- Casey -->
			<npc id="30062" x="19313" y="146229" z="-3064" heading="49152" respawnDelay="60" /> <!-- Sonia -->
			<npc id="30063" x="19223" y="146228" z="-3064" heading="49152" respawnDelay="60" /> <!-- Lars -->
			<npc id="30064" x="19708" y="144780" z="-3088" heading="40960" respawnDelay="60" /> <!-- Terry -->
			<npc id="30065" x="19725" y="144567" z="-3088" heading="32768" respawnDelay="60" /> <!-- Arnelle -->
			<npc id="30066" x="19516" y="144772" z="-3088" heading="49152" respawnDelay="60" /> <!-- Pabris -->
			<npc id="30067" x="16269" y="142461" z="-2688" heading="48400" respawnDelay="60" /> <!-- Glyvka -->
			<npc id="30068" x="16456" y="142447" z="-2688" heading="48400" respawnDelay="60" /> <!-- Shegfield -->
			<npc id="30069" x="16236" y="142153" z="-2688" heading="15600" respawnDelay="60" /> <!-- Rollant -->
			<npc id="30070" x="15795" y="142347" z="-2680" heading="61824" respawnDelay="60" /> <!-- Sylvain -->
			<npc id="30071" x="18199" y="146081" z="-3080" heading="41544" respawnDelay="60" /> <!-- Lucas -->
			<npc id="30072" x="17503" y="147575" z="-3120" heading="20703" respawnDelay="60" /> <!-- Metty -->
			<npc id="30073" x="15757" y="144638" z="-3080" heading="24825" respawnDelay="60" /> <!-- Jacob -->
			<npc id="30074" x="16937" y="144041" z="-3008" heading="36864" respawnDelay="60" /> <!-- Harlan -->
			<npc id="30075" x="18813" y="142439" z="-3048" heading="47500" respawnDelay="60" /> <!-- Xaber -->
			<npc id="30076" x="19044" y="142392" z="-3048" heading="47500" respawnDelay="60" /> <!-- Liam -->
			<npc id="30458" x="19737" y="143122" z="-3024" heading="29500" respawnDelay="60" /> <!-- Poitan -->
			<npc id="30459" x="19696" y="144336" z="-3088" heading="24576" respawnDelay="60" /> <!-- Wandius -->
			<npc id="30460" x="19472" y="144334" z="-3088" heading="8192" respawnDelay="60" /> <!-- Cardien -->
			<npc id="30461" x="16427" y="142131" z="-2688" heading="15600" respawnDelay="60" /> <!-- Mirien -->
			<npc id="30462" x="17168" y="146720" z="-3080" heading="2500" respawnDelay="60" /> <!-- Tronix -->
			<npc id="30463" x="17384" y="146605" z="-3080" heading="28672" respawnDelay="60" /> <!-- Ixia -->
			<npc id="30464" x="17280" y="146944" z="-3080" heading="45056" respawnDelay="60" /> <!-- Clayton -->
			<npc id="30465" x="21495" y="145728" z="-3144" respawnDelay="60" /> <!-- Herven -->
			<npc id="30466" x="21491" y="145968" z="-3152" respawnDelay="60" /> <!-- Bright -->
			<npc id="30469" x="21040" y="144608" z="-3064" heading="32768" respawnDelay="60" /> <!-- Jonas -->
			<npc id="30508" x="19932" y="143232" z="-3040" heading="63000" respawnDelay="60" /> <!-- Castor -->
			<npc id="30509" x="20040" y="143308" z="-2947" heading="63000" respawnDelay="60" /> <!-- Dowki -->
			<npc id="30510" x="19924" y="143196" z="-3040" heading="63000" respawnDelay="60" /> <!-- Somak -->
			<npc id="30594" x="21017" y="144481" z="-3064" heading="32768" respawnDelay="60" /> <!-- Ranspo -->
			<npc id="30595" x="19712" y="143307" z="-3024" heading="47152" respawnDelay="60" /> <!-- Opix -->
			<npc id="30608" x="19041" y="145964" z="-3064" heading="8192" respawnDelay="60" /> <!-- Maria -->
			<npc id="30620" x="20609" y="145993" z="-3120" heading="49152" respawnDelay="60" /> <!-- Emily -->
			<npc id="30625" x="20983" y="143844" z="-3072" heading="4096" respawnDelay="60" /> <!-- Mason -->
			<npc id="30629" x="16680" y="142368" z="-2688" heading="32768" respawnDelay="60" /> <!-- Rukal -->
			<npc id="30642" x="20000" y="143108" z="-3040" heading="63000" respawnDelay="60" /> <!-- Chianta -->
			<npc id="30644" x="19831" y="144514" z="-3096" respawnDelay="60" /> <!-- Kash -->
			<npc id="30654" x="17220" y="146554" z="-3080" heading="12288" respawnDelay="60" /> <!-- Sir Kiel Nighthawk -->
			<npc id="30735" x="19264" y="144672" z="-3096" heading="32768" respawnDelay="60" /> <!-- Sophya -->
			<npc id="30736" x="16955" y="146303" z="-3104" heading="28672" respawnDelay="60" /> <!-- Redfoot -->
			<npc id="30737" x="19079" y="145762" z="-3080" heading="49152" respawnDelay="60" /> <!-- Morgan -->
			<npc id="30767" x="18853" y="145939" z="-3072" heading="49152" respawnDelay="60"> <!-- Auctioneer -->
				<parameters>
					<param name="fnAgitMap" value="dion" />
				</parameters>
			</npc>
			<npc id="30828" x="19276" y="142864" z="-3032" heading="32768" respawnDelay="60" /> <!-- Waters -->
			<npc id="30956" x="17025" y="146070" z="-3080" heading="35523" respawnDelay="60" /> <!-- Nanarin -->
			<npc id="30957" x="18378" y="145052" z="-3072" heading="64312" respawnDelay="60" /> <!-- Swan -->
			<npc id="30959" x="20175" y="145480" z="-3112" heading="16384" respawnDelay="60" /> <!-- Barbado -->
			<npc id="30960" x="21025" y="144931" z="-3064" heading="40960" respawnDelay="60" /> <!-- Beer Chest -->
			<npc id="30961" x="19490" y="145930" z="-3064" respawnDelay="60" /> <!-- Clothes Chest -->
			<!-- <npc id="30990" x="15693" y="142886" z="-2696" heading="16000" respawnDelay="60" /> --> <!-- Lottery Ticket Seller -->
			<npc id="31031" x="20368" y="144912" z="-3088" respawnDelay="60" /> <!-- Broadcasting Tower -->
			<npc id="31043" x="19034" y="146249" z="-3064" heading="55264" respawnDelay="60" /> <!-- Octavia -->
			<npc id="31048" x="19505" y="146220" z="-3064" heading="42568" respawnDelay="60" /> <!-- McDermott -->
			<npc id="31092" x="16393" y="144916" z="-3016" heading="30000" respawnDelay="60" /> <!-- Black Marketeer of Mammon -->
			<npc id="31204" x="19306" y="142894" z="-3032" respawnDelay="60" /> <!-- Georgio -->
			<npc id="31418" x="16694" y="142336" z="-2688" heading="32000" respawnDelay="60" /> <!-- Rouke -->
			<npc id="31434" x="19600" y="143344" z="-3024" heading="56000" respawnDelay="60" /> <!-- Shaling -->
			<npc id="31441" x="19536" y="143072" z="-3024" heading="13000" respawnDelay="60" /> <!-- Gordo -->
			<npc id="31570" x="19539" y="145987" z="-3064" heading="32500" respawnDelay="60" /> <!-- Lanosco -->
			<npc id="31688" x="16304" y="144288" z="-2984" heading="55000" respawnDelay="60" /> <!-- Olympiad Manager -->
			<npc id="31690" x="16256" y="144256" z="-2992" heading="55000" respawnDelay="60" /> <!-- Monument of Heroes -->
			<npc id="32199" x="16259" y="146282" z="-3096" heading="63319" respawnDelay="60" /> <!-- Holst -->
			<npc id="32200" x="16279" y="146242" z="-3096" heading="63319" respawnDelay="60" /> <!-- Entien -->
			<npc id="32201" x="16292" y="146310" z="-3096" heading="63319" respawnDelay="60" /> <!-- Rindy -->
			<npc id="32327" x="15253" y="143036" z="-2672" heading="64751" respawnDelay="60" /> <!-- Adventurers' Guide -->
			<npc id="32478" x="20560" y="144768" z="-3080" heading="33000" respawnDelay="60" /> <!-- Dimensional Merchant -->
			<npc id="32480" x="17282" y="147500" z="-3120" heading="20480" respawnDelay="60" /> <!-- Ronde -->
			<npc id="32484" x="18228" y="146030" z="-3088" heading="41852" respawnDelay="60" /> <!-- Pathfinder Worker -->
			<npc id="32876" x="19626" y="143091" z="-3024" heading="22204" respawnDelay="60" /> <!-- Desian -->
			<npc id="33359" x="18890" y="145933" z="-3072" heading="49152" respawnDelay="60" /> <!-- Kerry -->
			<npc id="33496" x="19471" y="146214" z="-3064" heading="49990" respawnDelay="60" /> <!-- Diamis -->
			<npc id="33529" x="18794" y="145928" z="-3072" heading="50460" respawnDelay="60" /> <!-- Lanin -->
			<npc id="33587" x="15195" y="142947" z="-2672" heading="826" respawnDelay="60" /> <!-- Mentor Guide -->
			<npc id="33685" x="16234" y="144192" z="-2984" heading="59279" respawnDelay="60" /> <!-- Mysterious Butler -->
			<npc id="33825" x="15145" y="143472" z="-2672" heading="57049" respawnDelay="60" /> <!-- La Vie En Rose -->
			<npc id="33854" x="15209" y="143445" z="-2672" heading="42661" respawnDelay="60" /> <!-- Beauty Shop Helper -->
			<npc id="33855" x="15245" y="143421" z="-2680" heading="30784" respawnDelay="60" /> <!-- Beauty Shop Helper -->
			<npc id="33856" x="15197" y="143399" z="-2672" heading="15263" respawnDelay="60" /> <!-- Beauty Shop Helper -->
			<npc id="35145" x="19342" y="145105" z="-3104" heading="30304" respawnDelay="60" /> <!-- Manor Manager -->
			<npc id="35145" x="17882" y="144184" z="-3048" heading="54112" respawnDelay="60" /> <!-- Manor Manager -->
			<npc id="35402" x="17677" y="145282" z="-3048" heading="22500" respawnDelay="60" /> <!-- Borna -->
			<npc id="35403" x="17621" y="144920" z="-3032" heading="12288" respawnDelay="60" /> <!-- Ron -->
			<npc id="35404" x="18928" y="143391" z="-3024" respawnDelay="60" /> <!-- Jamal -->
			<npc id="35405" x="18634" y="143342" z="-3008" heading="64500" respawnDelay="60" /> <!-- Flynn -->
			<npc id="35406" x="20237" y="145941" z="-3120" heading="49152" respawnDelay="60" /> <!-- Jabilo -->
			<npc id="35407" x="19996" y="146216" z="-3112" heading="57344" respawnDelay="60" /> <!-- Seth -->
			<npc id="36706" x="17761" y="147436" z="-3120" heading="41828" respawnDelay="60" /> <!-- Mermoden -->
			<npc id="33946" x="15208" y="143141" z="-2678" heading="9760" respawnDelay="60" /> <!-- Adventure Guildsman -->
		</group>
	</spawn>
</list>

=== PowerAndMones/lineagehighfive/server/L2J_Mobius_CT_2.6_HighFive/dist/game/data/spawns/Dion/FloranVillage.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/spawns.xsd">
	<spawn name="FloranVillage">
		<group>
			<npc id="30078" x="16970" y="170391" z="-3496" heading="61440" /> <!-- Pano -->
			<npc id="30079" x="17836" y="169853" z="-3496" heading="20000" /> <!-- Barder -->
			<npc id="30609" x="17475" y="169556" z="-3496" heading="57344" /> <!-- Creta -->
			<npc id="30767" x="17328" y="170574" z="-3496" heading="56099"> <!-- Auctioneer -->
				<parameters>
					<param name="fnAgitMap" value="floran" />
				</parameters>
			</npc>
			<npc id="31571" x="17232" y="170528" z="-3496" heading="53000" /> <!-- Hufs -->
			<npc id="31773" x="17788" y="169842" z="-3496" heading="20000" /> <!-- Sonin -->
			<npc id="32478" x="17740" y="169800" z="-3496" heading="20000" /> <!-- Dimensional Merchant -->
			<npc id="36737" x="17278" y="169747" z="-3480" heading="49153" /> <!-- Gairin -->
			<npc id="36738" x="17262" y="169863" z="-3496" heading="16857" /> <!-- Ludina -->
			<npc id="36739" x="17870" y="170644" z="-3488" heading="15086" /> <!-- Flon -->
			<npc id="36740" x="17883" y="170537" z="-3504" heading="52191" /> <!-- Danif -->
			<npc id="30981" x="15520" y="174572" z="-3624" heading="57344" /> <!-- Dark Judge -->
			<npc id="30291" x="20943" y="171358" z="-3552" heading="12288" /> <!-- Alex -->
			<npc id="30633" x="13258" y="169790" z="-3704" heading="1000" /> <!-- Evert -->
			<npc id="30626" x="15734" y="174805" z="-3632" /> <!-- Hamil -->
			<npc id="30728" x="10699" y="171474" z="-3560" /> <!-- Leirynn -->
			<npc id="31031" x="17264" y="170160" z="-3496" heading="16384" /> <!-- Broadcasting Tower -->
		</group>
	</spawn>
</list>

=== PowerAndMones/lineagehighfive/server/L2J_Mobius_CT_2.6_HighFive/dist/game/data/spawns/Others/TrainingCamp.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/spawns.xsd">
	<spawn name="TrainingCamp">
		<npc id="4378" x="-114493" y="253597" z="-1536" heading="52509" respawnDelay="60" /> <!-- Manager -->
		<npc id="4378" x="-14131" y="123870" z="-3112" heading="39327" respawnDelay="60" /> <!-- Manager -->
		<npc id="4378" x="16122" y="142810" z="-2696" heading="15689" respawnDelay="60" /> <!-- Manager -->
		<npc id="4378" x="44008" y="-47770" z="-792" heading="53122" respawnDelay="60" /> <!-- Manager -->
		<npc id="4378" x="86993" y="-143248" z="-1288" heading="2058" respawnDelay="60" /> <!-- Manager -->
		<npc id="4378" x="82629" y="53097" z="-1488" heading="10250" respawnDelay="60" /> <!-- Manager -->
		<npc id="4378" x="83290" y="148397" z="-3400" heading="1154" respawnDelay="60" /> <!-- Manager -->
		<npc id="4378" x="111807" y="218957" z="-3536" heading="37605" respawnDelay="60" /> <!-- Manager -->
		<npc id="4378" x="147343" y="-55417" z="-2728" heading="55523" respawnDelay="60" /> <!-- Manager -->
		<npc id="4378" x="147239" y="25625" z="-2008" heading="13027" respawnDelay="60" /> <!-- Manager -->
		<npc id="18912" x="-56650" y="135938" z="-2672" heading="0" respawnDelay="60" /> <!-- Scarecrow -->
	</spawn>
</list>
